source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
target 'ExampleSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'TiniAppSDK', '~> 1.9.2'

end
post_install do |installer|  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end

    target.build_configurations.each do |config|
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
    end
    
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
